### PR TITLE
Lint fixes

### PR DESCRIPTION
**Pull request by stevenlyons**
* So many changes to remove major linting errors

### CODE REVIEW

**Comment by stevenlyons** [comment]
@daytime-em @jsanford8 most of these changes are really minor but a few that might matter (though no major changes on the SDK file so it should pretty safe, overall). Could you run this through the testing framework and see if any errors have cropped up?

**Review by jsanford8 — COMMENTED** [review]
code wise, looks good. We should run this through the tests, as well as on an actual device to make sure things are still working, but I'm good with the changes

**Review by daytime-em — APPROVED** [review]
✅ The tests pass, and lint is right by default ofc 

edit: Here are the [test logs](https://gist.github.com/daytime-em/5ca4963d5108132f3089a648bfd607fa)

**Comment by jsanford8** [comment]
@daytime-em do you happen to have a roku set in dev mode you can test with? I'm in the process of setting mine up again

**Comment by daytime-em** [comment]
@jsanford8 [Already gotcha](https://github.com/muxinc/roku-mux/pull/53#pullrequestreview-1618299511). I put the test logs in too, but the tl;dr is that they pass

**Comment by jsanford8** [comment]
@daytime-em oh I meant running the sample apps themselves and manually testing them... if that's even necessary any more

**Comment by jsanford8** [comment]
I couldn't get the linter to run myself, or tests, but Em did and I was able to run the app, so I think we're good here if you want to convert this from a draft @stevenlyons

**Pull request merged**
